### PR TITLE
Add warning during inspection time

### PR DESCRIPTION
**Pull request by aswna**
Add vibrate and verbal 8- and 12-second warnings during inspection time.

### CODE REVIEW

**Comment by aswna** [comment]
Related to #54 
(Messed up previous pull request when trying to update it.)

**Comment by aricneto** [comment]
Hey! I really liked the feature, but I did a few changes to the pull:

- First, and most importantly, I removed the TextToSpeech thing. If the user doesn't have a voice pack installed, Android will automatically, with no warning, trigger a voice pack download. If the download does not trigger (no internet, not enough space, acessibility features disabled...), the feature will not work, and there's no way for the app to know why exactly.
    - Instead, I went with a more foolproof way that supports any device by using ToneGenerator to make beep alerts for each inspection stage. It loses the "cool factor" of having it actually say the time left, but it's less of a hassle and doesn't need localization.
- I moved the Warning class to its own separate file, complete with a CountdownWarning.Builder, which makes the task of managing different settings easier. This change did not account for custom inspection durations, so I made it alert once the countdown reaches 50% and 80% of its total duration when the duration is not set to default (which is roughly when the official inspection alerts happen, if you divide 8/15 and 12/15).
- The user can now also set it to vibrate only, sound only, or both.

Thanks for the contribution!

**Comment by aswna** [comment]
> localization
IMO, the 8 and 12 seconds does not need localization, check the WCA regulations.
> countdown reaches 50% and 80%
Again, check the WCA regulations.

Link: https://www.worldcubeassociation.org/regulations/#A3d

So, I think it was more or less fine as I proposed.

**Comment by SpawnAliX** [comment]
I'm sorry to ask that, but I can't find how to activate this warning feature.
I don't have any option on the app (2.0.0 at this day).
Is it finnally released?

**Comment by aswna** [comment]
@SpawnAliX it was not updated since Dec 13, 2016 in Google Play...
I am afraid this app is not developed/maintained anymore (or only sporadically). :(

**Pull request merged**
