### PR TITLE
[Do not merge] Added support for using an external stackmat timer

### PR DESCRIPTION
**Pull request by freundTech**
This PR adds support for using an external stackmat timer (#70).

What currently works:

- [x] Reading timer value
- [x] Saving times when timer is stopped
- [x] Surviving activity restarts (If screen is rotated)
- [x] Toggling external timer on and off
- [x] Option to hide the switch in the Toolbar (People who don't have a timer probably don't want the switch in the toolbar all the time
- [x] Support for devices below Android 7.0

What needs to be done:

- [ ] Testing (There might be some edge cases)
- [ ] Better icon for switch
- [ ] Icon on switch sometimes vanishes...
- [ ] Somehow make it work with inspection

### CODE REVIEW

**Comment by aricneto** [comment]
Thanks! This has been a very requested feature for quite some time.
I don't have a StackMat so I won't be able to do much as far as the technical side goes, but if you want help in other things (icons/UX), just let me know.

**Comment by freundTech** [comment]
I could need some help with the UI. I don't really like how the switch is currently positioned, but I can't think of a better option. Also it could need a better icon.

And whenever the device is or was in landscape mode the off icon is completely missing for some reason (I'm pretty new to android development. Maybe I just overlooked something).

To get the switch to show up you first have to enable it in settings.

Unless you are running android 7.0 the app will probably crash when you change the switch to on. Just change AudioSource.UNPROCESSED to AudioSource.DEFAULT. That won't make it work on android < 7.0, but at least it won't crash ;)

Also I'm almost done with the <7.0 support.

**Comment by freundTech** [comment]
Update: I now got it 100% working on my device (except for the icon on the switch sometimes disappearing), however there are some more problems...

When I tested it on my brothers phone (OnePlus 3) the signal the phone recorded looked **nothing** like the signal my phone (LG G4) recorded, therefor completely breaking the signal parsing.

LG G4:
screenshot_20170413-164852

OnePlus3:
whatsapp image 2017-04-15 at 11 41 21 am

I'll try to find more testers so I can see on which phones it works and on which it doesn't.
I'll also re-enable the Android 7.0+only parsing method and make it automatically switch to whichever works on a given device.

**Comment by Combinacijusx** [comment]
For me signals look quite similar just on LG G4 amplitude is bigger or maybe i just displayed more squashed graph. Don't you think?

**Comment by freundTech** [comment]
@Combinacijusx Have you tested if external timer support works on you device or only looked at the sound wave? (I have a debug build [here](https://freundtech.com/downloads/twistytimer-debug2.apk))

Also can you tell me what phone you are using?

**Comment by Combinacijusx** [comment]
No, I haven't tested it because I don't have timer. 

My phone is Samsung Galaxy S3 Neo

**Comment by freundTech** [comment]
Closing this PR for now, because I haven't worked on it in a while. I'll reopen it if I continue working on it.

Also I moved all those changes from freundtech:master to freundtech:external_timer

**Pull request closed without merging**
