### PR TITLE
Removed prebuild dependencies and added dependencies from repository

### PR DESCRIPTION
**Pull request by freundTech**

### CODE REVIEW

**Comment by xaviershay** [comment]
Why?

(I'm new to Android development so trying to learn!)

**Comment by xaviershay** [comment]
oh I get it. Why were these in here as prebuilt in the first place? Maybe they didn't used to exist in the repo?

**Comment by freundTech** [comment]
Rebased against current master to fix merge conflicts

**Comment by aricneto** [comment]
Thanks!
I also had to add an extra parameter (8c28ffbcc960ad18f0f9b31da1a031f54de597e1) to a TNoodle function that gets called in the TrainerScrambler class due to the build version update.

**Pull request merged**
